### PR TITLE
Iiscrum 842

### PR DESCRIPTION
**Pull request by PeterJokinen**
- zabbix changes for test tool database monitor convertion, [Main PR](https://github.com/digiaiiris/iiris/pull/1128)
- some cosmetic fixes

### CODE REVIEW

**Review by sapajune — COMMENTED** [review]
Shouldn't test.inc.php be included in this PR? Otherwise Zabbix built from this branch would likely be broken.

**Comment by PeterJokinen** [comment]
> 
> 
> Shouldn't test.inc.php be included in this PR? Otherwise Zabbix built from this branch would likely be broken.

It would be, but this branch shouldn't really be used for anything else than creating the patch file, that is used to update an existing environment. Like we do when we build our version on top of monitoringartist zabbix. Then we add test.inc.php, and update the code to use it with patch file. Technically I think patch could also create the new test.inc.php file, but I didn't want to mix any new files to this branch.

**Comment by sapajune** [comment]
> > Shouldn't test.inc.php be included in this PR? Otherwise Zabbix built from this branch would likely be broken.
> 
> It would be, but this branch shouldn't really be used for anything else than creating the patch file, that is used to update an existing environment. Like we do when we build our version on top of monitoringartist zabbix. Then we add test.inc.php, and update the code to use it with patch file. Technically I think patch could also create the new test.inc.php file, but I didn't want to mix any new files to this branch.

I guess it depends on point of view. My comments:
- Keeping all of feature in one branch makes managing later changes easier.
- Having patch file contain full files doesn't have any downsides that I can think of.
- What if Zabbix adds file called test.inc.php later on? We won't notice it until our container build of Zabbix becomes suddenly broken. Also it will be hard to trace.
- Potentially this branch could be used to run modified Zabbix and develop the feature as standalone.

**Comment by PeterJokinen** [comment]
> 
> 
> > > Shouldn't test.inc.php be included in this PR? Otherwise Zabbix built from this branch would likely be broken.
> > 
> > 
> > It would be, but this branch shouldn't really be used for anything else than creating the patch file, that is used to update an existing environment. Like we do when we build our version on top of monitoringartist zabbix. Then we add test.inc.php, and update the code to use it with patch file. Technically I think patch could also create the new test.inc.php file, but I didn't want to mix any new files to this branch.
> 
> I guess it depends on point of view. My comments:
> 
>     * Keeping all of feature in one branch makes managing later changes easier.
> 
>     * Having patch file contain full files doesn't have any downsides that I can think of.
> 
>     * What if Zabbix adds file called test.inc.php later on? We won't notice it until our container build of Zabbix becomes suddenly broken. Also it will be hard to trace.
> 
>     * Potentially this branch could be used to run modified Zabbix and develop the feature as standalone.

Moved all new files inside the patch file (tested it, all seemed to work fine), updated this and the other PR accordingly.

**Review by sapajune — APPROVED** [review]
Good work!

**Review by bulkware — APPROVED** [review]

**Pull request merged**
